sudo: false
dist: bionic
language: python
matrix:
    - env: TOXENV=py37
    - env: TOXENV=black
    - env: TOXENV=flake8
    - env: TOXENV=docs
    - env: TOXENV=coverage
install:
    - pip install tox
script: tox
