name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  tox:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Python 3.9
            runs-on: ubuntu-latest
            python-version: 3.9
            toxenv: py39

          - name: Python 3.8
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: py38

          - name: Python 3.7
            runs-on: ubuntu-latest
            python-version: 3.7
            toxenv: py37

          - name: Coverage
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: coverage

          - name: Black
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: black

          - name: Flake8
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: flake8

          - name: Flake8
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: flake8

          - name: Build documentation and check warnings
            runs-on: ubuntu-latest
            python-version: 3.8
            toxenv: build-docs
